const FEISHU='https://open.feishu.cn/open-apis';
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff',...headers}});
class ApiError extends Error{constructor(message,status=400){super(message);this.status=status}}
let cachedToken;

function needEnv(env){if(!env.FEISHU_APP_ID||!env.FEISHU_APP_SECRET)throw new ApiError('后台尚未配置 FEISHU_APP_ID / FEISHU_APP_SECRET',503);if(!env.DB)throw new ApiError('后台尚未绑定 Cloudflare D1 数据库 DB',503)}
function adminAuth(request,env){const got=request.headers.get('x-admin-token')||'';if(!env.ADMIN_TOKEN||env.ADMIN_TOKEN.length<12)throw new ApiError('后台尚未配置 ADMIN_TOKEN',503);if(got!==env.ADMIN_TOKEN)throw new ApiError('管理员口令不正确',401)}
function checkOrigin(request){if(!['GET','HEAD'].includes(request.method)){const o=request.headers.get('origin');if(o&&o!==new URL(request.url).origin)throw new ApiError('不允许跨站写入',403)}}
async function token(env){if(cachedToken?.until>Date.now())return cachedToken.value;const r=await fetch(`${FEISHU}/auth/v3/tenant_access_token/internal`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({app_id:env.FEISHU_APP_ID,app_secret:env.FEISHU_APP_SECRET})});const d=await r.json();if(!r.ok||d.code!==0)throw new ApiError(`飞书授权失败：${d.msg||r.status}`,502);cachedToken={value:d.tenant_access_token,until:Date.now()+Math.max(0,(d.expire||7200)-120)*1000};return cachedToken.value}
async function fs(env,path,opt={}){const r=await fetch(FEISHU+path,{...opt,headers:{...(opt.body instanceof FormData?{}:{'content-type':'application/json'}),'authorization':`Bearer ${await token(env)}`,...(opt.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok||d.code!==0)throw new ApiError(`飞书请求失败（${d.code||r.status}）：${d.msg||'请检查应用权限'}`,r.status===429?429:r.status===403?403:502);return d.data||{}}
async function all(env,path,size=100){let items=[],page='',seen=new Set();do{const q=new URLSearchParams({page_size:String(size)});if(page)q.set('page_token',page);const d=await fs(env,`${path}?${q}`);items.push(...(d.items||[]));page=d.has_more?d.page_token:'';if(d.has_more&&(!page||seen.has(page)))throw new ApiError('飞书分页返回异常',502);seen.add(page)}while(page);return items}
function stable(v){if(Array.isArray(v))return v.map(stable);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])]));return v}
export async function revision(fields){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(stable(fields))));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
export function slugify(s=''){return String(s).trim().toLowerCase().replace(/[^a-z0-9\u4e00-\u9fa5]+/g,'-').replace(/^-+|-+$/g,'').slice(0,64)}
const roleDefs={title:['Subject','提示词名称','名称','标题','作品名称'],cover:['Image Preview','ImagePreview','预览图','效果图','参考图','封面','封面图片','图片'],prompt:['Lang_ZH','LangZH','中文提示词','正向提示词','提示词','Prompt','prompt'],negative:['Lang_NEG','Negative','负向提示词','反向提示词','Negative Prompt','negative prompt'],category:['分类','提示词分类','类型'],style:['风格','画风','风格分类'],model:['绘画工具','模型','生成模型','AI模型','平台'],tags:['标签','Tag','Tags'],source:['来源','来源链接','参考链接','原文链接'],status:['状态','提示词状态'],notes:['备注','说明','描述']};
export function autoMapping(fields=[]){const map={};for(const [role,names] of Object.entries(roleDefs)){let f=fields.find(x=>names.includes(x.field_name));if(!f&&role==='title')f=fields.find(x=>x.is_primary)||fields.find(x=>/^subject$/i.test(x.field_name||''));if(!f&&role==='cover')f=fields.find(x=>x.type===17&&/(image|preview|预览|封面|图片)/i.test(x.field_name||''))||fields.find(x=>x.type===17);if(!f&&role==='prompt')f=fields.find(x=>/lang[_-]?zh|中文.*提示|prompt.*zh/i.test(x.field_name||''));if(!f&&role==='model')f=fields.find(x=>/绘画工具|生成工具|模型|model|tool/i.test(x.field_name||''));if(!f&&role==='source')f=fields.find(x=>/来源|source/i.test(x.field_name||''));if(f)map[role]=f.field_name}return map}
async function resolveFeishu(env,url,override=''){let link;try{link=new URL(url)}catch{throw new ApiError('请输入完整飞书链接')}if(link.protocol!=='https:'||!/(^|\.)feishu\.cn$/.test(link.hostname))throw new ApiError('仅支持飞书链接');const m=link.pathname.match(/^\/(base|wiki)\/([A-Za-z0-9_-]+)/);if(!m)throw new ApiError('请使用多维表格或知识库内多维表格链接');let app=m[1]==='base'?m[2]:String(override||'').trim();if(m[1]==='wiki'&&!app){const d=await fs(env,`/wiki/v2/spaces/get_node?token=${m[2]}`);if(d.node?.obj_type!=='bitable')throw new ApiError('此知识库节点不是多维表格');app=d.node.obj_token}const tables=await all(env,`/bitable/v1/apps/${app}/tables`);const table=link.searchParams.get('table')||(tables.length===1?tables[0].table_id:'');if(!table)throw new ApiError('请打开具体数据表后复制包含 table= 的链接');if(!tables.some(t=>t.table_id===table))throw new ApiError('数据表不存在或应用无权访问');return{url:link.href,appToken:app,tableId:table,tableName:tables.find(t=>t.table_id===table)?.name||''}}
async function pageBySlug(env,slug,includeDisabled=false){const row=await env.DB.prepare(`SELECT * FROM pages WHERE slug=? ${includeDisabled?'':'AND enabled=1'} LIMIT 1`).bind(slug).first();if(!row)throw new ApiError('页面不存在',404);return normalizePage(row)}
function normalizePage(r){return{...r,enabled:Boolean(r.enabled),mapping:parseJSON(r.mapping_json,{}),display:parseJSON(r.display_json,{})}}
function parseJSON(s,f){try{return JSON.parse(s)||f}catch{return f}}
function publicPage(p){return{id:p.id,name:p.name,slug:p.slug,description:p.description,icon:p.icon,sort_order:p.sort_order,enabled:p.enabled,mapping:p.mapping,display:p.display}}
async function liveData(env,page){const base=`/bitable/v1/apps/${page.app_token}/tables/${page.table_id}`;const [fields,records]=await Promise.all([all(env,base+'/fields'),all(env,base+'/records',500)]);return{fields,records:await Promise.all(records.map(async r=>({...r,revision:await revision(r.fields||{})})))}}
function writeable(fields){return new Set(fields.filter(f=>!f.is_computed&&[1,2,3,4,5,7,13,15,17].includes(f.type)).map(f=>f.field_name))}
async function assetResponse(request,env){let r=await env.ASSETS.fetch(request);if(r.status!==404)return r;const u=new URL(request.url);u.pathname='/index.html';return env.ASSETS.fetch(new Request(u.toString(),{method:'GET',headers:request.headers}))}

export default{async fetch(request,env){const u=new URL(request.url);if(!u.pathname.startsWith('/api/'))return assetResponse(request,env);try{needEnv(env);checkOrigin(request);
  if(u.pathname==='/api/site'&&request.method==='GET'){
    const rows=(await env.DB.prepare('SELECT * FROM pages WHERE enabled=1 ORDER BY sort_order ASC,id ASC').all()).results||[];
    const title=(await env.DB.prepare("SELECT value FROM settings WHERE key='site_title'").first())?.value||'AI Prompt Gallery';
    const subtitle=(await env.DB.prepare("SELECT value FROM settings WHERE key='site_subtitle'").first())?.value||'灵感、提示词与视觉参考';
    return json({title,subtitle,pages:rows.map(r=>publicPage(normalizePage(r)))});
  }
  if(u.pathname==='/api/health'&&request.method==='GET')return json({ok:true,db:true,feishu:true});

  const pageDataMatch=u.pathname.match(/^\/api\/page\/([^/]+)\/data$/);
  if(pageDataMatch&&request.method==='GET'){
    const page=await pageBySlug(env,decodeURIComponent(pageDataMatch[1]));const data=await liveData(env,page);return json({page:publicPage(page),...data});
  }
  const recMatch=u.pathname.match(/^\/api\/page\/([^/]+)\/records(?:\/([^/]+))?$/);
  if(recMatch){const page=await pageBySlug(env,decodeURIComponent(recMatch[1]));const rid=recMatch[2]||'';const base=`/bitable/v1/apps/${page.app_token}/tables/${page.table_id}`;
    if(request.method==='POST'){const body=await request.json(),fields=await all(env,base+'/fields'),allowed=writeable(fields);if(!body.fields||Object.keys(body.fields).some(k=>!allowed.has(k)))throw new ApiError('包含不可写字段');const d=await fs(env,base+'/records',{method:'POST',body:JSON.stringify({fields:body.fields})});return json(d)}
    if(['PUT','DELETE'].includes(request.method)){if(!/^rec[A-Za-z0-9_-]+$/.test(rid))throw new ApiError('记录标识无效');const body=await request.json();if(!body.revision)throw new ApiError('缺少编辑版本',409);const cur=await fs(env,`${base}/records/${rid}`);if(await revision(cur.record.fields||{})!==body.revision)throw new ApiError('这条记录已在飞书或其他窗口修改，请同步后重试',409);if(request.method==='DELETE'){await fs(env,`${base}/records/${rid}`,{method:'DELETE'});return json({success:true})}const fields=await all(env,base+'/fields'),allowed=writeable(fields);if(!body.fields||Object.keys(body.fields).some(k=>!allowed.has(k)))throw new ApiError('包含不可写字段');const d=await fs(env,`${base}/records/${rid}`,{method:'PUT',body:JSON.stringify({fields:body.fields})});return json(d)}
  }
  const mediaMatch=u.pathname.match(/^\/api\/page\/([^/]+)\/media$/);
  if(mediaMatch&&request.method==='GET'){const page=await pageBySlug(env,decodeURIComponent(mediaMatch[1]));const ft=(u.searchParams.get('file_token')||'').trim(),field=(u.searchParams.get('field_id')||'').trim(),record=(u.searchParams.get('record_id')||'').trim();if(!ft||!field||!record)throw new ApiError('附件上下文不完整',400);const extra=JSON.stringify({bitablePerm:{tableId:page.table_id,attachments:{[field]:{[record]:[ft]}}}});const mu=new URL(`${FEISHU}/drive/v1/medias/${encodeURIComponent(ft)}/download`);mu.searchParams.set('extra',extra);const r=await fetch(mu,{headers:{authorization:`Bearer ${await token(env)}`}});if(!r.ok){let detail='';try{const d=await r.clone().json();detail=d.msg||d.message||''}catch{}throw new ApiError(`图片读取失败（${r.status}）：${detail||'请检查飞书附件权限'}`,r.status===400?400:r.status===403?403:502)}return new Response(r.body,{headers:{'content-type':r.headers.get('content-type')||'application/octet-stream','cache-control':'private,max-age=21600','x-content-type-options':'nosniff'}})}
  const uploadMatch=u.pathname.match(/^\/api\/page\/([^/]+)\/media\/upload$/);
  if(uploadMatch&&request.method==='POST'){const page=await pageBySlug(env,decodeURIComponent(uploadMatch[1]));const form=await request.formData(),file=form.get('file');if(!file||typeof file==='string')throw new ApiError('请选择图片');if(!file.type?.startsWith('image/'))throw new ApiError('仅支持图片');if(file.size>20*1024*1024)throw new ApiError('图片不能超过 20MB');const fd=new FormData();fd.set('file_name',file.name||`prompt-${Date.now()}.png`);fd.set('parent_type','bitable_image');fd.set('parent_node',page.app_token);fd.set('size',String(file.size));fd.set('file',file,file.name||`prompt-${Date.now()}.png`);const r=await fetch(`${FEISHU}/drive/v1/medias/upload_all`,{method:'POST',headers:{authorization:`Bearer ${await token(env)}`},body:fd});let d={};try{d=await r.json()}catch{}if(!r.ok||d.code!==0||!d.data?.file_token)throw new ApiError(`图片上传失败：${d.msg||r.status}`,502);return json({file_token:d.data.file_token})}

  if(u.pathname.startsWith('/api/admin/'))adminAuth(request,env);
  if(u.pathname==='/api/admin/health'&&request.method==='GET')return json({ok:true,feishuConfigured:Boolean(env.FEISHU_APP_ID&&env.FEISHU_APP_SECRET),db:true});
  if(u.pathname==='/api/admin/pages'&&request.method==='GET'){const rows=(await env.DB.prepare('SELECT * FROM pages ORDER BY sort_order ASC,id ASC').all()).results||[];return json({items:rows.map(normalizePage)})}
  if(u.pathname==='/api/admin/pages'&&request.method==='POST'){const b=await request.json();const name=String(b.name||'').trim();if(!name)throw new ApiError('请填写页面名称');const slug=slugify(b.slug||name);if(!slug)throw new ApiError('页面地址无效');const resolved=await resolveFeishu(env,b.feishu_url,b.app_token_override||'');const fields=await all(env,`/bitable/v1/apps/${resolved.appToken}/tables/${resolved.tableId}/fields`);const mapping=autoMapping(fields);const result=await env.DB.prepare('INSERT INTO pages(name,slug,description,icon,feishu_url,app_token,table_id,sort_order,enabled,mapping_json,display_json) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(name,slug,String(b.description||''),String(b.icon||'✦'),resolved.url,resolved.appToken,resolved.tableId,Number(b.sort_order)||0,b.enabled===false?0:1,JSON.stringify(mapping),JSON.stringify({})).run();return json({id:result.meta.last_row_id,slug,mapping,tableName:resolved.tableName},201)}
  const adminPageMatch=u.pathname.match(/^\/api\/admin\/pages\/(\d+)$/);
  if(adminPageMatch&&request.method==='PUT'){const id=Number(adminPageMatch[1]),old=await env.DB.prepare('SELECT * FROM pages WHERE id=?').bind(id).first();if(!old)throw new ApiError('页面不存在',404);const b=await request.json();let appToken=old.app_token,tableId=old.table_id,feishuUrl=old.feishu_url,mapping=parseJSON(old.mapping_json,{});if(b.feishu_url&&b.feishu_url!==old.feishu_url){const resolved=await resolveFeishu(env,b.feishu_url,b.app_token_override||'');appToken=resolved.appToken;tableId=resolved.tableId;feishuUrl=resolved.url;const fields=await all(env,`/bitable/v1/apps/${appToken}/tables/${tableId}/fields`);mapping=autoMapping(fields)}const name=String(b.name??old.name).trim();const slug=slugify(b.slug??old.slug);await env.DB.prepare('UPDATE pages SET name=?,slug=?,description=?,icon=?,feishu_url=?,app_token=?,table_id=?,sort_order=?,enabled=?,mapping_json=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(name,slug,String(b.description??old.description),String(b.icon??old.icon),feishuUrl,appToken,tableId,Number(b.sort_order??old.sort_order)||0,b.enabled===undefined?old.enabled:(b.enabled?1:0),JSON.stringify(mapping),id).run();return json({success:true,slug,mapping})}
  if(adminPageMatch&&request.method==='DELETE'){await env.DB.prepare('DELETE FROM pages WHERE id=?').bind(Number(adminPageMatch[1])).run();return json({success:true})}
  const fieldsMatch=u.pathname.match(/^\/api\/admin\/pages\/(\d+)\/fields$/);
  if(fieldsMatch&&request.method==='GET'){const row=await env.DB.prepare('SELECT * FROM pages WHERE id=?').bind(Number(fieldsMatch[1])).first();if(!row)throw new ApiError('页面不存在',404);const fields=await all(env,`/bitable/v1/apps/${row.app_token}/tables/${row.table_id}/fields`);return json({items:fields,mapping:parseJSON(row.mapping_json,{})})}
  const mapMatch=u.pathname.match(/^\/api\/admin\/pages\/(\d+)\/mapping$/);
  if(mapMatch&&request.method==='PUT'){const b=await request.json();const row=await env.DB.prepare('SELECT id FROM pages WHERE id=?').bind(Number(mapMatch[1])).first();if(!row)throw new ApiError('页面不存在',404);await env.DB.prepare('UPDATE pages SET mapping_json=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(JSON.stringify(b.mapping||{}),Number(mapMatch[1])).run();return json({success:true})}
  if(u.pathname==='/api/admin/settings'&&request.method==='PUT'){const b=await request.json();for(const [k,v] of Object.entries({site_title:b.site_title,site_subtitle:b.site_subtitle})){if(v!==undefined)await env.DB.prepare('INSERT INTO settings(key,value,updated_at) VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP').bind(k,String(v)).run()}return json({success:true})}
  return json({message:'接口不存在'},404)
}catch(e){return json({message:e.message||'服务器错误'},e.status||500)}}};
