const API='https://open.feishu.cn/open-apis';
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}});
class ApiError extends Error{constructor(message,status=400){super(message);this.status=status}}
let cached;
function creds(request,env){const appId=(request.headers.get('x-feishu-app-id')||env.FEISHU_APP_ID||'').trim(),appSecret=(request.headers.get('x-feishu-app-secret')||env.FEISHU_APP_SECRET||'').trim();if(!appId||!appSecret)throw new ApiError('请先填写飞书 App ID 和 App Secret',503);return{appId,appSecret}}
async function token(c){if(cached?.id===c.appId&&cached.secret===c.appSecret&&cached.until>Date.now())return cached.value;const r=await fetch(`${API}/auth/v3/tenant_access_token/internal`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({app_id:c.appId,app_secret:c.appSecret})});const d=await r.json();if(!r.ok||d.code!==0)throw new ApiError(`飞书授权失败：${d.msg||r.status}`,502);cached={id:c.appId,secret:c.appSecret,value:d.tenant_access_token,until:Date.now()+Math.max(0,(d.expire||7200)-120)*1000};return cached.value}
async function fs(c,path,opt={}){const r=await fetch(API+path,{...opt,headers:{'content-type':'application/json','authorization':`Bearer ${await token(c)}`,...(opt.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok||d.code!==0)throw new ApiError(`飞书请求失败（${d.code||r.status}）：${d.msg||'请检查应用权限'}`,r.status===429?429:502);return d.data||{}}
async function all(c,path,size=100){let items=[],page='',seen=new Set();do{const q=new URLSearchParams({page_size:String(size)});if(page)q.set('page_token',page);const d=await fs(c,`${path}?${q}`);items.push(...(d.items||[]));page=d.has_more?d.page_token:'';if(d.has_more&&(!page||seen.has(page)))throw new ApiError('飞书分页返回异常',502);seen.add(page)}while(page);return items}
function stable(v){if(Array.isArray(v))return v.map(stable);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])]));return v}
async function revision(fields){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(stable(fields))));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function checkOrigin(request){if(!['GET','HEAD'].includes(request.method)){const o=request.headers.get('origin');if(o&&o!==new URL(request.url).origin)throw new ApiError('不允许跨站写入',403)}}
export default{async fetch(request,env){const u=new URL(request.url);if(!u.pathname.startsWith('/api/'))return env.ASSETS.fetch(request);try{checkOrigin(request);const c=creds(request,env);
if(u.pathname==='/api/health')return json({ok:true});
if(u.pathname==='/api/resolve'&&request.method==='POST'){const {url,appToken:override}=await request.json();let link;try{link=new URL(url)}catch{throw new ApiError('请输入完整飞书链接')}if(link.protocol!=='https:'||!/(^|\.)feishu\.cn$/.test(link.hostname))throw new ApiError('仅支持飞书链接');const m=link.pathname.match(/^\/(base|wiki)\/([A-Za-z0-9_-]+)/);if(!m)throw new ApiError('请使用多维表格或知识库中的多维表格链接');let app=m[1]==='base'?m[2]:(override||'').trim();if(m[1]==='wiki'&&!app){const d=await fs(c,`/wiki/v2/spaces/get_node?token=${m[2]}`);if(d.node?.obj_type!=='bitable')throw new ApiError('此 Wiki 节点不是多维表格');app=d.node.obj_token}const tables=await all(c,`/bitable/v1/apps/${app}/tables`);const table=link.searchParams.get('table')||(tables.length===1?tables[0].table_id:'');if(!table)throw new ApiError('请打开具体数据表后复制包含 table= 的链接');if(!tables.some(t=>t.table_id===table))throw new ApiError('数据表不存在或应用无权访问');return json({url:link.href,appToken:app,tableId:table,name:tables.find(t=>t.table_id===table)?.name||''})}
const app=u.searchParams.get('app_token')||'',table=u.searchParams.get('table_id')||'';if(!/^[A-Za-z0-9_-]+$/.test(app)||!/^tbl[A-Za-z0-9_-]+$/.test(table))throw new ApiError('表格标识无效');const base=`/bitable/v1/apps/${app}/tables/${table}`;
if(u.pathname==='/api/fields'&&request.method==='GET')return json({items:await all(c,base+'/fields')});
if(u.pathname==='/api/records'&&request.method==='GET'){const items=await all(c,base+'/records',500);return json({items:await Promise.all(items.map(async r=>({...r,revision:await revision(r.fields||{})})))})}
if(u.pathname==='/api/records'&&['POST','PUT','DELETE'].includes(request.method)){const rid=u.searchParams.get('record_id'),body=await request.json();if(['PUT','DELETE'].includes(request.method)){if(!/^rec[A-Za-z0-9_-]+$/.test(rid||''))throw new ApiError('记录标识无效');if(!body.revision)throw new ApiError('缺少编辑版本',409);const cur=await fs(c,`${base}/records/${rid}`);if(await revision(cur.record.fields||{})!==body.revision)throw new ApiError('这条提示词已在飞书或其他窗口修改，请同步后重试',409)}if(request.method==='DELETE'){await fs(c,`${base}/records/${rid}`,{method:'DELETE'});return json({success:true})}const schema=await all(c,base+'/fields');const writable=new Set(schema.filter(f=>!f.is_computed&&[1,2,3,4,5,7,13,15,17,18,21].includes(f.type)).map(f=>f.field_name));if(!body.fields||Object.keys(body.fields).some(k=>!writable.has(k)))throw new ApiError('包含不可写字段');const d=await fs(c,base+'/records'+(rid?'/'+rid:''),{method:request.method,body:JSON.stringify({fields:body.fields})});return json(d)}
if(u.pathname==='/api/media'&&request.method==='GET'){const ft=(u.searchParams.get('file_token')||'').trim(),field=u.searchParams.get('field_id')||'',record=u.searchParams.get('record_id')||'';if(!ft||!field||!record)throw new ApiError('附件上下文不完整');const extra=JSON.stringify({bitablePerm:{tableId:table,attachments:{[field]:{[record]:[ft]}}}});const mu=new URL(`${API}/drive/v1/medias/${encodeURIComponent(ft)}/download`);mu.searchParams.set('extra',extra);const r=await fetch(mu,{headers:{authorization:`Bearer ${await token(c)}`}});if(!r.ok)throw new ApiError(`图片读取失败：${r.status}`,502);return new Response(r.body,{headers:{'content-type':r.headers.get('content-type')||'application/octet-stream','cache-control':'private,max-age=21600'}})}
if(u.pathname==='/api/media/upload'&&request.method==='POST'){const form=await request.formData(),file=form.get('file');if(!file||typeof file==='string')throw new ApiError('请选择图片');if(!file.type?.startsWith('image/'))throw new ApiError('仅支持图片');const fd=new FormData();fd.set('file_name',file.name||`prompt-${Date.now()}.png`);fd.set('parent_type','bitable_image');fd.set('parent_node',app);fd.set('size',String(file.size));fd.set('file',file,file.name||`prompt-${Date.now()}.png`);const r=await fetch(`${API}/drive/v1/medias/upload_all`,{method:'POST',headers:{authorization:`Bearer ${await token(c)}`},body:fd});let d={};try{d=await r.json()}catch{}if(!r.ok||d.code!==0||!d.data?.file_token)throw new ApiError(`图片上传失败：${d.msg||r.status}`,502);return json({file_token:d.data.file_token})}
return json({message:'接口不存在'},404)}catch(e){return json({message:e.message||'服务器错误'},e.status||500)}}};
export{revision};
